import { MigrationInterface, QueryRunner } from "typeorm";

export class EventoCambioEstadoReclamo1715744133255 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `CREATE TABLE reclamos.evento_cambio_estado
            (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START 100 ),
                idreclamo integer NOT NULL,
                estado reclamos.estado_reclamo NOT NULL,
                fecha_hora timestamp without time zone NOT NULL,
                observacion character varying(60),
                PRIMARY KEY (id),
                CONSTRAINT fk_evento_camibio_estado_reclamo FOREIGN KEY (idreclamo)
                    REFERENCES reclamos.reclamo (id) MATCH SIMPLE
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
                    NOT VALID
            )`
        );
        await queryRunner.query(
            `CREATE VIEW reclamos.vw_eventos_cambios_estados
            AS
            SELECT
               evento_cambio_estado.id,
               evento_cambio_estado.idreclamo,
               evento_cambio_estado.estado,
               evento_cambio_estado.fecha_hora AS fechahora,
               evento_cambio_estado.observacion
            FROM reclamos.evento_cambio_estado`
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE IF EXISTS reclamos.evento_cambio_estado`);
        await queryRunner.query(`DROP VIEW IF EXISTS reclamos.vw_eventos_cambios_estados`);
    }

}
